[package]
name = "telegramBot"
version = "0.1.0"
authors = ["toko"]
edition = "2018"

[dependencies]
telegram-bot = "0.6"
futures = "0.1"
tokio = "0.1"
tokio-core = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.3.0"
regex = "1"
rand = "0.7.0"