[package]
name = "telegramBot"
version = "0.1.0"
authors = ["toko"]
edition = "2018"

[dependencies]
telegram-bot = "*"
futures = "*"
tokio = "*"
tokio-core = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "*"
regex = "*"